version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: corequeue
      POSTGRES_PASSWORD: corequeue
      POSTGRES_DB: corequeue
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"  

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/corequeue;
      /usr/bin/mc anonymous set public myminio/corequeue;
      exit 0;
      "

  api:
    build:
      context: ../..
      dockerfile: deploy/docker/api.Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg://corequeue:corequeue@db:5432/corequeue
      REDIS_URL: redis://redis:6379/0
      ALLOWED_ORIGINS: http://localhost:3000,http://localhost
      DATA_ROOT: /data
      STORAGE_BACKEND: s3
      S3_ENDPOINT_URL: http://minio:9000
      S3_BUCKET_NAME: corequeue
      S3_ACCESS_KEY_ID: minioadmin
      S3_SECRET_ACCESS_KEY: minioadmin
      S3_REGION: us-east-1
    command: uvicorn apps.api.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
      - redis
      - minio
    ports:
      - "8000:8000"
    volumes:
      - ../../apps/api:/app/apps/api
      - ../../packages/common:/app/packages/common
      - ../../data:/data

  worker:
    build:
      context: ../..
      dockerfile: deploy/docker/worker.Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg://corequeue:corequeue@db:5432/corequeue
      REDIS_URL: redis://redis:6379/0
      DATA_ROOT: /data
    depends_on:
      - api
      - db
      - redis
    command: python -m apps.worker.main
    volumes:
      - ../../apps/worker:/app/apps/worker
      - ../../packages/common:/app/packages/common

  web:
    build:
      context: ../..
      dockerfile: deploy/docker/web.Dockerfile
    depends_on:
      - api
    ports:
      - "3000:3000"
    volumes:
      - ../../apps/web:/app/apps/web
      - /app/apps/web/node_modules
      - ../../packages/common:/app/packages/common
      - ../../data:/data:ro

  nginx:
    image: nginx:1.27
    volumes:
      - ../../infra/nginx/nginx.local.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - web
    ports:
      - "80:80"

volumes:
  db_data: {}
  minio_data: {}
